name: CI
on: [ push ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: moneymeets/action-setup-python-poetry@master

      - uses: moneymeets/moneymeets-composite-actions/lint-python@master

      - run: poetry run pytest --cov
