# This file was added by Pulumi and should not be edited manually. To edit the contents of this file, please go
# to the github-management project in moneymeets-pulumi and call `pulumi up` after changing the template file.

name: Merge checks

on:
  push:
    branches:
      - feature/**

jobs:
  merge-checks:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, '[skip checks]')"
    timeout-minutes: 5
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Merge checks
        uses: moneymeets/action-merge-checks@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head_sha: ${{ github.sha }}
