name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish-package:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: moneymeets/action-setup-python-poetry@master

      - name: Publish package
        run: |
          sed -i -e "s/1+SNAPSHOT/0.$(date +"%Y%m%d%H%M")/" pyproject.toml
          git rev-parse HEAD > VERSION.txt
          poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
